# Generated by Django 4.1.1 on 2022-09-27 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Названия модели')),
                ('engine', models.CharField(blank=True, max_length=1000, verbose_name='Двигатель модели')),
                ('hp', models.IntegerField(blank=True, null=True, verbose_name='лошадинные силы')),
                ('nm', models.IntegerField(blank=True, null=True, verbose_name='мощность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
        ),
    ]
